# Maven with SonarCloud analysis
# Build and run tests for Maven projects
# and analyse on SonarCloud
#
# * If necessary, create an endpoint to connect to SonarCloud
#
# * Set the sonarCloudXXX variables below
#
# * Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/en-gb/azure/devops/pipelines/customize-pipeline?view=azure-devops
 
trigger:
- master
 
pool:
 vmImage: 'ubuntu-20.04'
 
steps:

- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis configuration'
  inputs: 
   SonarCloud: 'sonarcloud'
   organization: 'tuto07'
   scannerMode: Other
   # Additional properties that will be passed to the scanner,
   # Put one key=value per line, example:
   # sonar.exclusions=**/*.bin
   extraProperties: |
      sonar.projectKey=tuto07_sonar-cloud-lab2
      sonar.organization=tuto07
     # sonar.coverage.jacoco.xmlReportPaths=CCReport43F6D5EF/jacoco.xml
     # Initial behavior of Maven task is that the SonarScanner uses information contained in Maven
     # object model to provide smart defaults for most of the standard analysis parameters.
     # You can however override this by setting wanted properties in this extraProperties space.
     # Read more about this : https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-maven/#header-4
- task: Maven@3
  displayName: 'Execute Maven verify'
  inputs:
   mavenPomFile: 'pom.xml'
   options: '-Dmaven.test.failure.ignore=true'
   mavenOptions: '-Xmx3072m'
   mavenVersionOption: 'Default'
   javaHomeOption: 'JDKVersion'
   jdkVersionOption: '1.11'
   jdkArchitectureOption: 'x64'
   publishJUnitResults: true
   mavenAuthenticateFeed: false
   effectivePomSkip: false
   sonarQubeRunAnalysis: true
   sqMavenPluginVersionChoice: 'latest'
   # codeCoverageToolOption: 'JaCoCo'
   testResultsFiles: '**/TEST-*.xml'
   goals: 'verify'
 
 
# Uncomment the next task to wait until SonarCloud processing has
# finished and to publish the result on the Pipeline build summary
- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
   pollingTimeoutSec: '300'

- task: Maven@3
  displayName: 'Execute Maven package'
  inputs:
   mavenPomFile: 'pom.xml'
   mavenOptions: '-Xmx3072m'
   javaHomeOption: 'JDKVersion'
   jdkVersionOption: '1.11'
   jdkArchitectureOption: 'x64'
   publishJUnitResults: false
   goals: 'package -DskipTests=true'

- task: CopyFiles@2
  displayName: 'Copy artifacts'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/target/*.?(war|jar)'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    artifactName: MyBuildOutputs